# Generated by Django 3.0.3 on 2020-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('complete_by', models.CharField(max_length=100)),
                ('started_on', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
